version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: buysket_db
    restart: always
    environment:
      POSTGRES_USER: postgresnew
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: buysket_backend
    command: npm run dev
    ports:
      - "5000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: postgres
      DB_USER: postgresnew
      DB_PASSWORD: 1234
      DB_NAME: db
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: buysket_frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  postgres_data:
